package programmesplant
import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.jdbc.Predef._
import Headers._
import com.excilys.ebi.gatling.http.Headers.Names._
import akka.util.duration._
import bootstrap._
import assertions._

object AdminEditorScenario {

	val adminscn = scenario("Admin Editor Scenario")
		.exec(http("request_index_page_1")
					.get("/2014/ug/programmes")
			)
		.pause(28 milliseconds)
		.exec(http("request_2")
					.get("/css/style.css")
					.headers(headers_2)
					.check(status.in(Seq(200, 304)))
			)
		.pause(4)
		.exec(http("request_leaflets_page_1")
					.get("/2014/ug/leaflets")
			)
		.pause(17)
		.exec(http("request_leaflets_edit_67_1")
					.get("/2014/ug/leaflets/edit/67")
			)
		.pause(14)
		.exec(http("request_leaflets_save_67_1")
					.post("/2014/ug/leaflets/edit")
					.headers(headers_5a)
						.param("""id""", """67""")
						.param("""name""", """Sport and Exercise for Health Studies""")
						.param("""campus""", """1""")
						.param("""tracking_code""", """http://uk.sitestat.com/kent/kent-ext/s?courses.pdfs.sports-studies-pdf&ns_type=pdf&ns_url=http://www.kent.ac.uk/courses/pdfs/sports-studies.pdf""")
			)
		.pause(3)
		.exec(http("request_leaflets_create_1")
					.get("/2014/ug/leaflets/create")
			)
		.pause(15)
		.exec(http("request_leaflets_create_save_1")
					.post("/2014/ug/leaflets/create")
					.headers(headers_5a)
						.param("""name""", """A new test leaflet""")
						.param("""campus""", """2""")
						.param("""tracking_code""", """http://www.kent.ac.uk""")
			)
		.pause(2)
		.exec(http("request_index_page_2")
					.get("/2014/ug/programmes")
			)
		.pause(7)
		.exec(http("request_programme_edit_235_1")
					.get("/2014/ug/programmes/edit/235")
			)
		.pause(1)
		.exec(http("request_10")
					.get("/js/ckeditor/skins/moono/editor_gecko.css")
					.headers(headers_10a)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.exec(http("request_11")
					.get("/js/ckeditor/lang/en-gb.js")
					.headers(headers_11)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.pause(1)
		.exec(http("request_12")
					.get("/js/ckeditor/styles.js")
					.headers(headers_12)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.pause(22)
		.exec(http("request_programme_save_235_1")
					.post("/2014/ug/programmes/edit")
					.headers(headers_13)
						.fileBody("ProgrammesPlantAdmin_request_13.txt")
			)
		.pause(1)
		.exec(http("request_14")
					.get("/js/ckeditor/skins/moono/editor_gecko.css")
					.headers(headers_10a)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.exec(http("request_15")
					.get("/js/ckeditor/lang/en-gb.js")
					.headers(headers_11)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.pause(1)
		.exec(http("request_16")
					.get("/js/ckeditor/styles.js")
					.headers(headers_12)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.pause(21)
		.exec(http("request_18")
					.get("http://fonts.googleapis.com/css")
					.headers(headers_18)
					.queryParam("""family""", """Ubuntu""")
			)
		.pause(6)
		.exec(http("request_programme_live_235_1")
					.get("/2014/ug/programmes/235/make_live/3418")
			)
		.pause(1)
		.exec(http("request_20")
					.get("/js/ckeditor/skins/moono/editor_gecko.css")
					.headers(headers_10a)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.exec(http("request_21")
					.get("/js/ckeditor/lang/en-gb.js")
					.headers(headers_11)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.pause(1)
		.exec(http("request_22")
					.get("/js/ckeditor/styles.js")
					.headers(headers_12)
					.queryParam("""t""", """D08E""")
					.check(status.in(Seq(200, 304)))
			)
		.pause(4)
		.exec(http("request_programme_index_3")
					.get("/2014/ug/programmes")
			)
		.pause(405 milliseconds)
		.exec(http("request_programme_index_4")
					.get("/2014/ug/programmes")
			)
}